# smart_contracts/pieout/errors.py
from typing import Final

# Define assert error messages
INVALID_CREATOR: Final[str] = "Transaction sender address must match application creator address."
INVALID_GAME_ID: Final[str] = "Box game state not found. Check if Game ID is valid."
INVALID_GAME_EVENT_ID: Final[str] = "Game event not found. Check if Game Event ID is valid"
INVALID_PLAYER: Final[str] = "Transaction sender is not recognized as a valid player for this game."
INVALID_MANAGER: Final[str] = "Transaction sender is not recognized as valid manager address for this game."
INVALID_WINNER: Final[str] = "Transaction sender is not recognized as valid winner address for this game."
INVALID_BOX_PAY_SENDER: Final[str] = "Box payment sender address must match transaction sender address."
INVALID_BOX_PAY_RECEIVER: Final[str] = "Box payment receiver address must match application address."
INVALID_BOX_PAY_FEE: Final[str] = "Insufficient funds. Box pay amount is not enough to cover application MBR."
INVALID_STAKE_PAY_SENDER: Final[str] = "Stake payment sender address must match transaction sender address."
INVALID_STAKE_PAY_RECEIVER: Final[str] = "Stake payment receiver address must match application address."
INVALID_STAKE_PAY_FEE: Final[str] = "Insufficient funds. Stake pay amount is not enough to cover application MBR."
INVALID_GROUP_SIZE: Final[str] = "Invalid group size. Ensure number of transaction in group is within bounds."
INVALID_MINT_PAY_SENDER: Final[str] = "Mint payment sender address must match transaction sender address."
INVALID_MINT_PAY_RECEIVER: Final[str] = "Mint payment receiver address must match application address."
INVALID_MINT_PAY_FEE: Final[str] = "Insufficient funds. Mint pay amount is not enough to cover application MBR."
STANDALONE_TXN_ONLY: Final[str] = "Invalid group size. This app call only appproves standalone transactions."
UNAUTH_ADDR: Final[str] = "Transaction sender is not an authorized caller."
PLAYER_CAP_OVERFLOW: Final[str] = "Player cap overflow. Max players limit must not be exceeded."
PLAYER_ACTIVE: Final[str] = "Transaction sender is already recognized as a valid player for this game."
NON_ZERO_ACTIVE_PLAYERS: Final[str] = "Game lobby not empty. Number of active players must be zero."
NON_ZERO_PRIZE_POOL: Final[str] = "Prize pool not empty. Amount in prize pool must be zero."
FULL_GAME_LOBBY: Final[str] = "Number of active players must not exceed number of max players."
DEADLINE_EXPIRED: Final[str] = "Phase deadline expired. Latest block timestamp must not exceed expiry timestamp."
STAKING_FINAL: Final[str] = "Game state staking finalized value mismatch."
BOX_P_START_POS_OVERFLOW: Final[str] = "Players box start position index overflow. Can not store more addresses."
MANAGER_SOLE_PLAYER: Final[str] = "Manager account must be sole active player in game."
COMMIT_ROUND_NOT_REACHED: Final[str] = "Randomness commit round not reached yet."
BOX_FOUND: Final[str] = "Box found. Ensure the box you are trying to access does not exist already."
BOX_NOT_FOUND: Final[str] = "Box not found. Ensure the box you are trying to access was created and still exists."
COMMIT_RAND_GAME_ID_MISMATCH: Final[str] = "Game ID mismatch. Game ID argument must match box commit rand game ID."
DELETEABLE_NOT_TRUE: Final[str] = "Template variable 'DELETABLE' needs to be 'True' at deploy-time."
