# smart_contracts/pieout/errors.py
from typing import Final

# Define assert error messages
INVALID_CREATOR: Final[str] = "Account must match application creator address."
INVALID_MAX_PLAYERS: Final[str] = "The number of max players must be within bounds."
INVALID_CALLER: Final[str] = "Account is not authorized to make this call."
INVALID_ADMIN: Final[str] = "Account is not recognized as the admin address for this game."
INVALID_TROPHY_RECEIVER: Final[str] = "Asset trophy receiver must match application ATH address."
INVALID_BOX_PAY_SENDER: Final[str] = "Box payment sender address must match transaction sender address."
INVALID_BOX_PAY_RECEIVER: Final[str] = "Box payment receiver address must match application address."
INVALID_BOX_PAY_FEE: Final[str] = "Insufficient funds. Box pay amount is not enough to cover application MBR."
INVALID_STAKE_PAY_SENDER: Final[str] = "Stake payment sender address must match transaction sender address."
INVALID_STAKE_PAY_RECEIVER: Final[str] = "Stake payment receiver address must match application address."
INVALID_STAKE_PAY_FEE: Final[str] = "Insufficient funds. Stake pay amount is not enough to cover staking requirements."
INVALID_MINT_PAY_SENDER: Final[str] = "Mint payment sender address must match transaction sender address."
INVALID_MINT_PAY_RECEIVER: Final[str] = "Mint payment receiver address must match application address."
INVALID_MINT_PAY_FEE: Final[str] = "Insufficient funds. Mint pay amount is not enough to cover asset creation cost."
INVALID_GROUP_SIZE: Final[str] = "Invalid group size. Ensure number of transaction in group is within valid bounds."
INVALID_GROUP_IDX: Final[str] = "Invalid group index. Ensure transaction group index matches the expected value. "
INVALID_GAME_ID: Final[str] = "Invalid Game ID. Box Commit Rand Game ID must be a certain value or match Game ID arg."
INVALID_METHOD_SELECTOR: Final[str] = "Transaction at this group index must have exact required method selector."
GAME_ID_NOT_FOUND: Final[str] = "Box game state not found. Check if game ID exists."
PLAYER_NOT_FOUND: Final[str] = "Account is not recognized as an active player for this game."
TRIGGER_ID_NOT_FOUND: Final[str] = "Game event not found. Check if game event Trigger ID exists"
BOX_NOT_FOUND: Final[str] = "Box not found. Ensure the box you are trying to access was created and still exists."
BOX_FOUND: Final[str] = "Box found. Ensure the box you are trying to access does not exist already."
STANDALONE_TXN_ONLY: Final[str] = "Invalid group size. This app call can only take standalone transactions."
PLAYER_ACTIVE: Final[str] = "Player with this address must not be an active game participant in the game."
NON_ZERO_ACTIVE_PLAYERS: Final[str] = "Game lobby not empty. Number of active players must be zero."
NON_ZERO_PRIZE_POOL: Final[str] = "Prize pool not empty. Amount in prize pool must be zero."
NON_ZERO_COMMIT_RAND_ROUND: Final[str] = "Commit Rand Round not empty. Value must be zero to obtain a valid one."
FULL_GAME_LOBBY: Final[str] = "Number of active players must not exceed number of max players."
TIME_CONSTRAINT_VIOLATION: Final[str] = "Invalid time frame. Call made outside the permitted block or timestamp range."
STAKING_FINAL_FLAG: Final[str] = "Game state staking finalized boolean value mismatch."
HOSTING_GAME_FLAG: Final[str] = "Game register hosting game boolean value mismatch."
BOX_P_START_POS_OVERFLOW: Final[str] = "Players box start position index overflow. Can not store more addresses."
ADMIN_SOLE_PLAYER: Final[str] = "Game admin address must be sole remaining active player in the game."
SENDER_MISMATCH: Final[str] = "Sender mismatch. Sender must be same address across all transactions in group."
APP_ID_MISMATCH: Final[str] = "Application ID mismatch. App ID must be same across all transactions in group."
COMMIT_RAND_ROUND_NOT_REACHED: Final[str] = "Randomness commit round not reached yet."
COMMIT_RAND_START_VALUES: Final[str] = "Box Commit Rand fields must not have their default starting values."
ASSET_OPT_IN_REQUIRED: Final[str] = "Account must be opted in to asset in order to perform this action."
DELETEABLE_NOT_TRUE: Final[str] = "Template variable 'DELETABLE' needs to be 'True' at deploy-time."
